export const GET_ARTICLES = 'GET_ARTICLES';
export const ADD_ARTICLE = 'GET_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SAVE_USERINFO = 'SAVE_USERINFO'
export const SET_AUTH_LOADING = 'SET_LOADING'
export const RESET_AUTH_LOADING = 'RESET_LOADING'
export const SAVE_AUTH_SUCCESS = 'SAVE_AUTH_SUCCESS'

export const SAVE_USER_INFO_IN_LOCAL_STORAGE = 'SAVE_USER_INFO_IN_LOCAL_STORAGE'
export const DELETE_USER_INFO_FROM_LOCAL_STORAGE = 'DELETE_USER_INFO_FROM_LOCAL_STORAGE'